twig:
    paths:
        '%kernel.project_dir%/templates/app': 'app'
        '%kernel.project_dir%/templates/admin': 'admin'
    form_themes:
        - '@app/shared/layout/form_theme.html.twig'
    default_path: '%kernel.project_dir%/templates'
    date:
        format: 'd M Y H:i'
        interval_format: '%d days'
        timezone: null
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'

when@test:
    twig:
        strict_variables: true
