framework:
    validation:
        email_validation_mode: html5
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
