vich_uploader:
    db_driver: orm
    metadata:
        auto_detection: false
        cache: file
        directories:
            - {
                path: '%kernel.project_dir%/src/Infrastructure/Authentication/Filesystem/Mapping',
                namespace_prefix: 'Domain\Authentication'
            }
            - {
                  path: '%kernel.project_dir%/src/Infrastructure/Content/Filesystem/Mapping',
                  namespace_prefix: 'Domain\Content'
            }

    mappings:
        auth_user_avatar:
            uri_prefix: '/uploads/authentication/user/avatar'
            upload_destination: '%kernel.project_dir%/public/uploads/authentication/user/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        # Blog
        content_blog_attachment:
            uri_prefix: '/uploads/content/blog/attachment'
            upload_destination: '%kernel.project_dir%/public/uploads/content/blog/attachment'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y' # will create directory "2018/23/09" for curent date "2018-09-23"
                    date_time_property: created_at # see above example
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        content_blog_post_thumbnail:
            uri_prefix: '/uploads/content/blog/post/thumbnail'
            upload_destination: '%kernel.project_dir%/public/uploads/content/blog/post/thumbnail'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug', transliterate: true }

        # Podcast
        content_podcast_season_thumbnail:
            uri_prefix: '/uploads/content/podcast/season/thumbnail'
            upload_destination: '%kernel.project_dir%/public/uploads/content/podcast/season/thumbnail'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug', transliterate: true }

        content_podcast_episode_thumbnail:
            uri_prefix: '/uploads/content/podcast/episode/thumbnail'
            upload_destination: '%kernel.project_dir%/public/uploads/content/podcast/episode/thumbnail'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug', transliterate: true }

        content_podcast_episode_audio:
            uri_prefix: '/streaming/podcasts'
            upload_destination: '%kernel.project_dir%/public/uploads/content/podcast/episode/audio'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug', transliterate: true }

        # Training
        content_training_video_thumbnail:
            uri_prefix: '/uploads/content/video/thumbnail'
            upload_destination: '%kernel.project_dir%/public/uploads/content/video/thumbnail'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug', transliterate: true }

        content_training_technology_thumbnail:
            uri_prefix: '/uploads/content/technology/thumbnail'
            upload_destination: '%kernel.project_dir%/public/uploads/content/technology/thumbnail'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug', transliterate: true }
