version: '3'

services:
  database:
    image: mariadb:10.7.3
    container_name: devscast_community_database
    restart: unless-stopped
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: devscast
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
    volumes:
      - database-data:/var/lib/mysql:rw
      - ./var:/var/www/var
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  web:
    image: nginx:alpine
    container_name: devscast_community_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:delegated
      - ./tools/config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    user: '${USER_ID}:${GROUP_ID}'
    container_name: devscast_community_php
    restart: unless-stopped
    build:
      context: ./tools/docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database

  redis:
    image: redis:6-alpine
    container_name: devscast_community_redis
    restart: unless-stopped
    labels:
      com.symfony.server.service-prefix: 'REDIS'

  ## Development Tools
  maildev:
    image: mailhog/mailhog
    container_name: devscast_community_maildev
    ports:
      - "1080:8025"
    labels:
      com.symfony.server.service-prefix: 'MAILER'

  adminer:
    image: adminer:4.8.1
    container_name: devscast_community_adminer
    restart: unless-stopped
    depends_on:
      - database
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8082:8080"

  node:
    container_name: devscast_community_node
    restart: unless-stopped
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: ./tools/docker/node
    command: yarn run watch
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"

  php_test:
    user: '${USER_ID}:${GROUP_ID}'
    container_name: devscast_community_phptest
    restart: unless-stopped
    build:
      context: ./tools/docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database_test

  database_test:
    image: mariadb:10.7.3
    container_name: devscast_community_databasetest
    restart: unless-stopped
    environment:
      MARIADB_USER: test
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: devscast
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'

  redis_gui:
    image: rediscommander/redis-commander
    container_name: devscast_community_redisgui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  database-data:
    driver:
      local
