# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: './domains/*.yaml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    devscast.administration.default_sidebar: Infrastructure\Shared\Symfony\Twig\UI\MainSidebar

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Fixtures\:
        resource: '../fixtures/*'

    Application\:
        resource: '../src/Application'

    Domain\:
        resource: '../src/Domain'

    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude:
            - '../src/Infrastructure/Shared/Symfony/Kernel.php'

    Symfony\Component\DependencyInjection\ContainerInterface:
        alias: 'service_container'

    Infrastructure\Shared\Symfony\Twig\UI\MainSidebar:
        public: true
