parameters:
    content.podcast_episode.upload_path: '%kernel.project_dir%/public/uploads/content/podcast_episode/audio'
    content.video.upload_path: '%kernel.project_dir%/public/uploads/content/video'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Doctrine Repositories
    Domain\Content\Repository\CategoryRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\CategoryRepository'
    Domain\Content\Repository\CommentRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\CommentRepository'
    Domain\Content\Repository\ContentRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\ContentRepository'
    Domain\Content\Repository\PodcastEpisodeRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\PodcastEpisodeRepository'
    Domain\Content\Repository\PodcastSeasonRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\PodcastSeasonRepository'
    Domain\Content\Repository\PostRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\PostRepository'
    Domain\Content\Repository\PostListRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\PostListRepository'
    Domain\Content\Repository\PostSeriesRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\PostSeriesRepository'
    Domain\Content\Repository\ProgressionRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\ProgressionRepository'
    Domain\Content\Repository\RatingRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\RatingRepository'
    Domain\Content\Repository\SubjectProposalRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\SubjectProposalRepository'
    Domain\Content\Repository\SubjectProposalVoteRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\SubjectProposalVoteRepository'
    Domain\Content\Repository\TagRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\TagRepository'
    Domain\Content\Repository\TechnologyRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\TechnologyRepository'
    Domain\Content\Repository\VideoRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\VideoRepository'
    Domain\Content\Repository\AttachmentRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\AttachmentRepository'
