parameters:
    content.podcast_episode.upload_path: '%kernel.project_dir%/uploads/content/podcast_episode/audio'
    content.video.upload_path: '%kernel.project_dir%/uploads/content/video'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Doctrine Repositories
    Domain\Content\Repository\CategoryRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\CategoryRepository'
    Domain\Content\Repository\CommentRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\CommentRepository'
    Domain\Content\Repository\ContentRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\ContentRepository'
    Domain\Content\Repository\PodcastEpisodeRepositoryInterface: '@EpisodeRepository'
    Domain\Content\Repository\PodcastSeasonRepositoryInterface: '@SeasonRepository'
    Domain\Content\Repository\PostRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\PostRepository'
    Domain\Content\Repository\ProgressionRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\ProgressionRepository'
    Domain\Content\Repository\TagRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\TagRepository'
    Domain\Content\Repository\TechnologyRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\TechnologyRepository'
    Domain\Content\Repository\VideoRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\VideoRepository'
    Domain\Content\Repository\AttachmentRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\AttachmentRepository'
    Domain\Content\Repository\ContentViewRepositoryInterface: '@Infrastructure\Content\Doctrine\Repository\ContentViewRepository'
