name: Lint
on: [ push, pull_request ]
jobs:
  lint:
    name: Coding style standard and static analysis check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        run: make lint
