name: Test
on: [ push, pull_request ]
jobs:
  test:
    name: PHPUnit Symfony Testing
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false

    steps:
      -   name: Checkout
          uses: actions/checkout@v2

      -   name: Start mysql service
          run: sudo systemctl start mysql

      -   name: Run tests
          run: make test
          env:
            DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/devscast
