name: Test
on: [ push, pull_request ]
jobs:
  test:
    name: PHPUnit Symfony Unit and Functional Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        run: make test
